version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/myapp
    command: bundle exec rails server -p 3000 -b '0.0.0.0'

  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
